### ISSUE TITLE
Nutrient wash-off 

### ISSUE THREAD

**Issue by christophe-rd** [christophe-rd/fuelinex#18]
Hi @lizzieinvancouver @FrederikBaumgarten !
Our plan of washing off nutrients from the fall-nutrient-boosted trees is compromised! The water will be cut soon, so there won't be a way we can do a nutrient addition to the non-nitro-boosted trees as we planned.  
To clear up our goal was to add nutrients in September to nutrient-boosted trees and add nutrients during dormancy to the other trees at some point in the winter. 
This cannot be done. Here are the choices Lizzie and I discussed:
1. Wash off nutrient-boosted trees at the end of warm-fall treatment i.e. October 31st. The other trees won't get any fall nutrient addition. 
2. Add nutrients to the non-nutrient-boosted trees on October 31st and wash off all the trees just before the water gets cut (this might not be possible depending on when they cut it). 

Note:  the water isn't something I can negotiate, as I understand it's controlled for the whole campus.

**Comment by christophe-rd** [comment]
They should shut the water around mid-November unless there is a risk of frost before.

**Comment by lizzieinvancouver** [comment]
@christophe-rd Or what about don't wash them off and add nutrients to non-boosted trees in January or such ... as I think all the trees might need a boost.

**Comment by christophe-rd** [comment]
After discussing with Rob, here's what came out of the conversation: 

> We discussed whether we should give the non-nutrient-boosted trees the same amount of nutrients in the spring that the nutrient-boosted trees received in the fall. Since we didn’t want to compromise the main experiment because of the fall nutrient-boost treatment, we thought we shouldn’t do it. Rob is also not excited about this treatment and doesn’t see the point. 
> Therefore, since the trees will be bigger and in bigger pots, they should receive more nutrients than last year. We thought we should add twice as many nutrients in total as last year, but more frequently. We would add nutrients in April, May, June, and July and we’ll see how they are doing in August. What do you think?

Lizzie replied: 

> For the nutrient thing: I am fine with adding nutrients in April, May, June, and July but will you add nutrients now to the non-fall nutrient addition trees? I am worried about avoiding confounding fall nutrient addition with extra nutrients ....

I replied: 

> I thought not, because of the differences between the blocks. The trees outside the greenhouse will get rain all winter (nutrients will get washed off) while the trees in the greenhouse won’t. Therefore here’s what I thought:
> Next summer, the non-nutrient-boosted trees will get a “normal” dose 4 times while the nutrient boosted will get a “reduced dose” also 4 times. At the end of the growing season, all treatments will have received the exact same amount of nutrients, but at different times
> 

This is what we decided to do for now

**Comment by lizzieinvancouver** [comment]
@christophe-rd Thanks for all your work on figuring this out!
